<script lang="ts">
  import Text from '$lib/components/Wrapper/Text.svelte';
</script>

<div class="bg-secondary p-16">
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
  <Text text="Kontakt" />
</div>
