<script lang="ts">
  import Text from '$lib/components/Wrapper/Text.svelte';
</script>

<div class="bg-primary p-16">
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
  <Text text="Interessen" />
</div>
